### ISSUE TITLE
This still in the pipes?

### ISSUE THREAD

**Issue by gl33mer** [minsulander/unityhelikit#1]
This looks like one of those rare gifts.

Still plan on having a Unity3d integration kit?

**Comment by minsulander** [comment]
Yes, absolutely. This being a side project, I won't promise any release date, but I'm working on it. 

Just out of curiosity (and motivation), do you have any specific ideas on what you'll use it for?

**Comment by gl33mer** [comment]
Wasn't expecting a date and won't hold you to it.

Happy to hear it's happening.  No specific ideas (multi-prop drone simulation?).

**Comment by gl33mer** [comment]
Oh, wow. Looks great!
