### ISSUE TITLE
Why does main rotor heeling?

### ISSUE THREAD

**Issue by Oyshoboy** [minsulander/unityhelikit#2]
Hey! I have a small question, when a helicopter is hovering, main rotor is heeling one side.
Changed Min Lat Cyclic and it's helped a bit, but anyway not fully. 

Main rotor is heeling but helicopter is not moving 

![f0af3c113d](https://user-images.githubusercontent.com/23486183/36376212-56e0a28a-1583-11e8-9eaa-df16da546366.jpg)

**Comment by minsulander** [comment]
Hi there. It's called *translating tendency* or *tail rotor drift* and is something that is prevalent in all conventional single main rotor helicopters. Typically compensated for by pilot input or tilting the main rotor mast.

You can read more about it [here](http://helicopterflight.net/transtend.php), [here](http://www.danubewings.com/helicopter-translating-tendency-drift/), or [watch this video](https://www.youtube.com/watch?v=iW2595pbtOY)

**Comment by Oyshoboy** [comment]
@minsulander ah got it ! Thank you for answer!

**Comment by Oyshoboy** [comment]
@minsulander ah got it ! Thank you for answer!
